# Enable true color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g mouse on
set -g history-limit 10000

set -g base-index 1
set -g pane-base-index 1

unbind C-b
set -g prefix C-s

bind C-s send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded tmux config!"

unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Open new window in current path
bind c new-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Toggle zoom
bind -r m resize-pane -Z

unbind v
bind v copy-mode

# Moving window
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# Switch windows
bind C-h previous-window
bind C-l next-window

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Drag copy using mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

bind-key g display-popup -d '#{pane_current_path}' -w80% -h80% -E lazygit
bind-key f display-popup -d '#{pane_current_path}' -w80% -h80% -E fish
bind-key o display-popup -d '#{pane_current_path}' -w80% -h80% -E nnn
bind-key a display-popup -d '#{pane_current_path}' -w80% -h80% -E opencode

set -g status-justify centre
set -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "janoamaral/tokyo-night-tmux"


set -g @tokyo-night-tmux_date_format hide
set -g @tokyo-night-tmux_time_format 12H 
set -g @tokyo-night-tmux_show_music 0
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_terminal_icon 
set -g @tokyo-night-tmux_active_terminal_icon 
set -g @tokyo-night-tmux_window_tidy_icons 1
set -g @tokyo-night-tmux_window_id_style none

run '~/.config/tmux/plugins/tpm/tpm'
